server:
  port: 8082

spring:
  application:
    name: hotel-service
  datasource:
    url: jdbc:postgresql://localhost:5432/micro-dbs
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  main:
    banner-mode: "off"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9090/eureka